site_name: Wavy Node
site_url: https://wavynode.com
repo_url: https://github.com/WavyNode
theme: 
  name: material
  locale: es
  language: es
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: indigo
